{% set name = "plek2" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/AHinsu/plek2.git

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy ==1.19.2
    - pandas
    - keras ==2.4.3
    - tensorflow ==2.4.1
    - biopython >=1.3.2
    - regex

test:
  commands:
    - python -c "import PLEK2"

about:
  home: https://github.com/AHinsu/plek2
  license: MIT
  summary: 'PLEK2: a novel method for predicting lncRNA and mRNA based on sequence intrinsic features and Coding-Net model'
  description: |
    PLEK2 is an upgraded version of PLEK for predicting long non-coding RNAs (lncRNAs) 
    and messenger RNAs (mRNAs) based on k-mer scheme and deep learning. It uses sequence 
    intrinsic features and a Coding-Net model to distinguish between coding and non-coding 
    RNA sequences.
  doc_url: https://github.com/AHinsu/plek2
  dev_url: https://github.com/AHinsu/plek2

extra:
  recipe-maintainers:
    - AHinsu
